name: flutter_web_view
description: A web view plugin for Flutter. Works with iOS and Android
version: 0.0.1
author:
homepage:

flutter:
  plugin:
    androidPackage: com.apptreesoftware.flutterwebview
    pluginClass: FlutterWebViewPlugin

dependencies:
  flutter:
    sdk: flutter
